In [1]:
from sklearn.feature_extraction.text import CountVectorizer


In [2]:
corpus=['this is the first document',
       'this document is the second document',
       'and this is the third one',
       'is this the first document?']

In [3]:
corpus

['this is the first document',
 'this document is the second document',
 'and this is the third one',
 'is this the first document?']

In [4]:
vectorizer=CountVectorizer()

In [5]:
vectorizer

CountVectorizer()

In [6]:
vector=vectorizer.fit_transform(corpus)

In [7]:
vectorizer.vocabulary_

{'this': 8,
 'is': 3,
 'the': 6,
 'first': 2,
 'document': 1,
 'second': 5,
 'and': 0,
 'third': 7,
 'one': 4}

In [8]:
vector

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 21 stored elements in Compressed Sparse Row format>

In [9]:
feature_names=vectorizer.get_feature_names_out()
feature_names

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [10]:
vector.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [11]:
vector[0].toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [12]:
"""
corpus=['this is the first document',
       'this document is the second document',
       'and this is the third one',
       'is this the first document?']
"""

"\ncorpus=['this is the first document',\n       'this document is the second document',\n       'and this is the third one',\n       'is this the first document?']\n"

In [13]:
vectorizer=CountVectorizer(binary=True)
vector=vectorizer.fit_transform(corpus)
vector.toarray()

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)

In [14]:
vectorizer2=CountVectorizer(ngram_range=(1,1))
vector2=vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [15]:
len(vectorizer2.get_feature_names_out())

9

In [16]:
vectorizer3=CountVectorizer(ngram_range=(2,2))
vector3=vectorizer3.fit_transform(corpus)
vectorizer3.get_feature_names_out()

array(['and this', 'document is', 'first document', 'is the', 'is this',
       'second document', 'the first', 'the second', 'the third',
       'third one', 'this document', 'this is', 'this the'], dtype=object)

In [17]:
len(vectorizer3.get_feature_names_out())

13

In [18]:
"""
corpus=['this is the first document',
       'this document is the second document',
       'and this is the third one',
       'is this the first document?']
"""

"\ncorpus=['this is the first document',\n       'this document is the second document',\n       'and this is the third one',\n       'is this the first document?']\n"

In [19]:
vectorizer3=CountVectorizer(ngram_range=(3,3))
vector3=vectorizer3.fit_transform(corpus)
vectorizer3.get_feature_names_out()


array(['and this is', 'document is the', 'is the first', 'is the second',
       'is the third', 'is this the', 'the first document',
       'the second document', 'the third one', 'this document is',
       'this is the', 'this the first'], dtype=object)

In [20]:
len(vectorizer3.get_feature_names_out())

12

In [21]:
vectorizer3=CountVectorizer(ngram_range=(1,3))
vector3=vectorizer3.fit_transform(corpus)
vectorizer3.get_feature_names_out()

array(['and', 'and this', 'and this is', 'document', 'document is',
       'document is the', 'first', 'first document', 'is', 'is the',
       'is the first', 'is the second', 'is the third', 'is this',
       'is this the', 'one', 'second', 'second document', 'the',
       'the first', 'the first document', 'the second',
       'the second document', 'the third', 'the third one', 'third',
       'third one', 'this', 'this document', 'this document is',
       'this is', 'this is the', 'this the', 'this the first'],
      dtype=object)

In [22]:
len(vectorizer3.get_feature_names_out())

34

# TFIDF

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
tfidf=TfidfVectorizer()

In [25]:
vector2=tfidf.fit_transform(corpus)
tfidf.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [26]:
vector2.toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])

In [27]:
"""
corpus=['this is the first document',
       'this document is the second document',
       'and this is the third one',
       'is this the first document?']
"""

"\ncorpus=['this is the first document',\n       'this document is the second document',\n       'and this is the third one',\n       'is this the first document?']\n"

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()
vectors=vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(vectors.toarray())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [29]:
vectorizer.idf_

array([1.91629073, 1.22314355, 1.51082562, 1.        , 1.91629073,
       1.91629073, 1.        , 1.91629073, 1.        ])

In [30]:
vectorizer=TfidfVectorizer(use_idf=False,norm='l1')
vectors=vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(vectors.toarray())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0.         0.2        0.2        0.2        0.         0.
  0.2        0.         0.2       ]
 [0.         0.33333333 0.         0.16666667 0.         0.16666667
  0.16666667 0.         0.16666667]
 [0.16666667 0.         0.         0.16666667 0.16666667 0.
  0.16666667 0.16666667 0.16666667]
 [0.         0.2        0.2        0.2        0.         0.
  0.2        0.         0.2       ]]


In [31]:
"""
corpus=['this is the first document',
       'this document is the second document',
       'and this is the third one',
       'is this the first document?']
"""

"\ncorpus=['this is the first document',\n       'this document is the second document',\n       'and this is the third one',\n       'is this the first document?']\n"

In [32]:
vectorizer=TfidfVectorizer(use_idf=False,norm='l2')
vectors=vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(vectors.toarray())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0.         0.4472136  0.4472136  0.4472136  0.         0.
  0.4472136  0.         0.4472136 ]
 [0.         0.70710678 0.         0.35355339 0.         0.35355339
  0.35355339 0.         0.35355339]
 [0.40824829 0.         0.         0.40824829 0.40824829 0.
  0.40824829 0.40824829 0.40824829]
 [0.         0.4472136  0.4472136  0.4472136  0.         0.
  0.4472136  0.         0.4472136 ]]


In [33]:
0.4472136**2 + 0.4472136**2  + 0.4472136**2 +0.4472136**2 + 0.4472136**2 

1.0000000201248

In [34]:
vectorizer=TfidfVectorizer(use_idf=False)
vectors=vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
print(vectors.toarray())

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']
[[0.         0.4472136  0.4472136  0.4472136  0.         0.
  0.4472136  0.         0.4472136 ]
 [0.         0.70710678 0.         0.35355339 0.         0.35355339
  0.35355339 0.         0.35355339]
 [0.40824829 0.         0.         0.40824829 0.40824829 0.
  0.40824829 0.40824829 0.40824829]
 [0.         0.4472136  0.4472136  0.4472136  0.         0.
  0.4472136  0.         0.4472136 ]]


# Word2Vec

In [35]:
#This repository hosts the word2vec pre-trained Google News corpus (3 billion running words) word vector model (3 million 300-dimension English word vectors).
#https://stackoverflow.com/questions/46433778/import-googlenews-vectors-negative300-bin
#https://www.kaggle.com/datasets/leadbest/googlenewsvectorsnegative300

In [36]:
from gensim.models import Word2Vec
from gensim.models import KeyedVectors

In [37]:
!ls

Bag Of Words.ipynb
GoogleNews-vectors-negative300.bin


In [39]:
w2v_model=KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin',binary=True)

In [40]:
type(w2v_model)

gensim.models.keyedvectors.KeyedVectors

In [41]:
print(w2v_model.most_similar('great'))

[('terrific', 0.7989331483840942), ('fantastic', 0.7935212254524231), ('tremendous', 0.7748856544494629), ('wonderful', 0.7647868990898132), ('good', 0.7291510105133057), ('incredible', 0.7032873630523682), ('marvelous', 0.6971103549003601), ('phenomenal', 0.6841564178466797), ('amazing', 0.6634127497673035), ('awesome', 0.6510507464408875)]


In [42]:
print(w2v_model.most_similar('worst'))

[('Worst', 0.6146092414855957), ('weakest', 0.6143776774406433), ('scariest', 0.5957258939743042), ('ugliest', 0.5931181311607361), ('best', 0.5835110545158386), ('bleakest', 0.5718506574630737), ('strongest', 0.5671454668045044), ('nastiest', 0.5644308924674988), ('lousiest', 0.5631451606750488), ('toughest', 0.5624395608901978)]


In [43]:
print(w2v_model.most_similar('tasty'))

[('delicious', 0.8730388283729553), ('scrumptious', 0.8007041215896606), ('yummy', 0.7856924533843994), ('flavorful', 0.7420164346694946), ('delectable', 0.7385422587394714), ('juicy_flavorful', 0.7114803791046143), ('appetizing', 0.7017217874526978), ('crunchy_salty', 0.7012301087379456), ('flavourful', 0.6912213563919067), ('flavoursome', 0.6857702732086182)]


In [44]:
print(w2v_model.most_similar('tasti'))

KeyError: "Key 'tasti' not present"

In [50]:
print(w2v_model.most_similar('microsoft',topn=3))

[('adobe_photoshop', 0.8042365908622742), ('microsoft_office', 0.7978680729866028), ('windows_xp', 0.7926486134529114)]


In [46]:
word_index=w2v_model.key_to_index['king']
word_index

6147

In [47]:
word_at_index=w2v_model.index_to_key[6147]
word_at_index

'king'

In [53]:
w2v_model.similarity(w1='ugly',w2='bad')

0.5263173

In [59]:
w2v_model.doesnt_match(['cricket','football','meditation'])

'meditation'

In [55]:
vec=w2v_model['king']-w2v_model['man']+w2v_model['woman']

In [57]:
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [56]:
w2v_model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300518155097961),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676948547363),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613664388656616),
 ('sultan', 0.5376776456832886),
 ('Queen_Consort', 0.5344247221946716),
 ('queens', 0.5289887189865112)]